name: My ERP release 
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release Version
        required: true
        
       developmentVersion:
              description: "Default version to use for new local working copy (-SNAPSHOT appended)"
        required: true
        

jobs:
  maven_release:
    name: Maven Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github

      - name: Configure Git user
        run: |
          git config user.email "optinfra.masum@gmail.com"
          git config user.name "masumcse1"

      - name: Perform release & publish artifacts
        run: mvn release:prepare release:perform -B -e -U -s $GITHUB_WORKSPACE/settings.xml --file pom.xml -DreleaseVersion=${{ github.event.inputs.releaseVersion }}  -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}-SNAPSHOT -DautoVersionSubmodules=true -Dtag=${{ github.event.inputs.releaseVersion }} -DreleaseOption="-DskipTests=true -Dmaven.javadoc.skip=true" -Dresume=false -Dmaven.site.skip=true -DgenerateReports=false -Dmaven.javadoc.skip=true  
        env:
          GITHUB_TOKEN: ${{ github.token }}

